version: '3.8'

services:
  rag-ai:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - chat-ebook-network
networks:
  chat-ebook-network:
    external: true
